declare @NumeroRemessa varchar(6)
set @NumeroRemessa = 

 (Select distinct top 1 IN03_NUMERO_REMESSA
         From IN01_TABELAO_INFRACAO 
         Left Join IN03_CABECALHO on IN03_COD_CABECALHO = FKIN01IN03_COD_CABECALHO 
         Left Join IN04_NAT_NIP on IN04_COD_NAT_NIP = FKIN03IN04_COD_NAT_NIP 
         where FKIN04IN05_COD_CLIENTE = 1
         And IN04_COD_NAT_NIP = 8201
         And  IN03_COD_CABECALHO_1 Is null )

select
 cast(IN01_TipoRegistro as varchar) 
+'|' + IN01_COD_LOCAL_OCORRENCIA
+'|' + replicate('0',2)+cast(IN01_NUM_REMESSA as varchar)
+'|' + isnull(cast(IN01_DATA_REMESSA as varchar), '0000-00-00')
+'|' + cast(IN01_COD_ORGAO_AUTUADOR as varchar) 
+'|' + IN01_DES_ORGAO_AUTUADOR + replicate(' ', (40-len(IN01_DES_ORGAO_AUTUADOR)))
+'|' + IN01_AUTO_INFRACAO + replicate(' ', (10-len(IN01_AUTO_INFRACAO)))
+'|' + cast( cast(IN01_DATA_HORA_COMETIMENTO as date) as varchar) + ' ' + cast( left(cast(IN01_DATA_HORA_COMETIMENTO as time),5) as varchar)
+'|' + IN01_LOCAL_COMETIMENTO + replicate(' ', (60-len(IN01_LOCAL_COMETIMENTO)))
+'|' + IN01_PLACA_VEICULO
+'|' + IN01_UF_PLACA
+'|' + IN01_IDENTIFICACAO_AGENTE + replicate(' ', (11-len(IN01_IDENTIFICACAO_AGENTE)))
+'|' + IN01_DES_MODELO + replicate(' ', (45-len(IN01_DES_MODELO)))
+'|' + IN01_CATEGORIA_VEICULO + replicate(' ', (30-len(IN01_CATEGORIA_VEICULO)))
+'|' + IN01_TIPO_VEICULO + replicate(' ', (16-len(IN01_TIPO_VEICULO)))
+'|' + IN01_COR_VEICULO + replicate(' ', (10-len(IN01_COR_VEICULO)))
+'|' + isnull(cast(IN01_DATA_AFERICAO as varchar),'0000-00-00')
+'|' + IN01_PROPRIETARIO + replicate(' ', (44-len(IN01_PROPRIETARIO)))
+'|' + IN01_ENDERECO + replicate(' ', (40-len(IN01_ENDERECO)))
+'|' + IN01_COMPLEMENTO_BAIRRO + replicate(' ', (40-len(IN01_COMPLEMENTO_BAIRRO)))
+'|' + replicate('0', 8 - len(cast(IN01_CEP as varchar))) + cast(IN01_CEP as varchar)
+'|' + IN01_CIDADE + replicate(' ', (20-len(IN01_CIDADE))) 
+'|' + IN01_UF_ENDERECO
+'|' + IN01_DES_INFRACAO + replicate(' ', (50-len(IN01_DES_INFRACAO))) 
+'|' + IN01_ARTIGO + replicate(' ', (19-len(IN01_ARTIGO))) 
+'|' + IN01_VEL_AFERIDA
+'|' + IN01_VEL_PERMITIDA
+'|' + IN01_VEL_CONSIDERADA
+'|' + IN01_PENALIDADE + replicate(' ', (8-len(IN01_PENALIDADE))) 
+'|' + replicate('0', (9-len(replace(cast(IN01_VALOR_INFRACAO as varchar),'.', '')))) + replace(cast(IN01_VALOR_INFRACAO as varchar),'.', '')
+'|' + replicate('0', 5 - len(cast(IN01_COD_MUNICIPIO as varchar))) + cast(IN01_COD_MUNICIPIO as varchar)
+'|' + isnull(cast(IN01_DATA_EMISSAO as varchar),'0000-00-00')
+'|' + isnull(cast(IN01_DATA_VENCIMENTO as varchar), '0000-00-00')
+'|' + IN01_NUM_CONTROLE
+'|' + IN01_VALOR_DA_BARRA
+'|' + IN01_CODIDO_BARRAS + replicate(' ', (48-len(IN01_CODIDO_BARRAS))) 
+'|' + IN01_PRONTUARIO
+'|' + IN01_UF_PRONTUARIO + replicate(' ', (2-len(IN01_UF_PRONTUARIO))) 
+'|' + IN01_CODIGO_RETORNO
+'|' + IN01_SEQUENCIAL + replicate(' ', (6-len(IN01_SEQUENCIAL)))
+'|' + replicate('0', 4 - len(cast(IN01_NUMERO_PONTOS as varchar))) + cast(IN01_NUMERO_PONTOS as varchar)
+'|' + replicate('0', 11 - len(IN01_COD_INFRAEST)) + IN01_COD_INFRAEST
+'|' + IN01_COD_INFRACAO
+'|' + IN01_ESPECIE_VEICULO + replicate(' ', (15-len(IN01_ESPECIE_VEICULO))) 

+'|' + IN04_CARTAO_POSTAGEM
+'|' + IN04_NUMERO_CONTRATO
+'|' + IN04_SERVICO_ADICIONAL
+'|' + IN04_IDENTIFIC_ARQ_SPOOL
+'|' + IN04_NOME_ARQ_SPOOL
+'|' + IN04_IDENTIFIC_ARQ_COMPLEM
+'|' + IN04_NOME_ARQ_COMPLEM
+'|' + IN04_NUM_END_DESTINATARIO
+'|' + IN04_COMPLEM_END_DESTINATARIO
+'['    as LINHA

from IN01_TABELAO_INFRACAO
left join IN03_CABECALHO on IN03_COD_CABECALHO = FKIN01IN03_COD_CABECALHO
left join IN04_NAT_NIP on IN04_COD_NAT_NIP = FKIN03IN04_COD_NAT_NIP
where FKIN04IN05_COD_CLIENTE =  1
and IN04_COD_NAT_NIP = 8201
      --  and IN01_PROCESSADO = 0 
       -- and IN03_COD_CABECALHO_1 is null 

--8182
--8183
--8201
--select * from IN04_NAT_NIP


/*

select
IN01_TipoRegistro
,IN01_COD_LOCAL_OCORRENCIA
,IN01_NUM_REMESSA
,IN01_DATA_REMESSA
,IN01_COD_ORGAO_AUTUADOR
,IN01_DES_ORGAO_AUTUADOR
,IN01_AUTO_INFRACAO
,IN01_DATA_HORA_COMETIMENTO
,IN01_LOCAL_COMETIMENTO
,IN01_PLACA_VEICULO
,IN01_UF_PLACA
,IN01_IDENTIFICACAO_AGENTE
,IN01_DES_MODELO
,IN01_CATEGORIA_VEICULO
,IN01_TIPO_VEICULO
,IN01_COR_VEICULO
,IN01_DATA_AFERICAO
,IN01_PROPRIETARIO
,IN01_ENDERECO
,IN01_COMPLEMENTO_BAIRRO
,IN01_CEP
,IN01_CIDADE
,IN01_UF_ENDERECO
,IN01_DES_INFRACAO
,IN01_ARTIGO
,IN01_VEL_AFERIDA
,IN01_VEL_PERMITIDA
,IN01_VEL_CONSIDERADA
,IN01_PENALIDADE
,IN01_VALOR_INFRACAO
,IN01_COD_MUNICIPIO  
,IN01_DATA_EMISSAO
,IN01_DATA_VENCIMENTO
,IN01_NUM_CONTROLE
,IN01_VALOR_DA_BARRA
,IN01_CODIDO_BARRAS
,IN01_PRONTUARIO
,IN01_UF_PRONTUARIO
,IN01_CODIGO_RETORNO
,IN01_SEQUENCIAL
,IN01_NUMERO_PONTOS
,IN01_COD_INFRAEST
,IN01_COD_INFRACAO
,IN01_ESPECIE_VEICULO

,IN04_CARTAO_POSTAGEM
,IN04_NUMERO_CONTRATO
,IN04_SERVICO_ADICIONAL
,IN04_IDENTIFIC_ARQ_SPOOL
,IN04_NOME_ARQ_SPOOL
,IN04_IDENTIFIC_ARQ_COMPLEM
,IN04_NOME_ARQ_COMPLEM
,IN04_NUM_END_DESTINATARIO
,IN04_COMPLEM_END_DESTINATARIO
from  IN01_TABELAO_INFRACAO
left join IN03_CABECALHO on IN03_COD_CABECALHO = FKIN01IN03_COD_CABECALHO
left join IN04_NAT_NIP on IN04_COD_NAT_NIP = FKIN03IN04_COD_NAT_NIP

*/